on:
  workflow_dispatch
  
name: Nightly Spinups
jobs:
  AFG:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ISO: ["BFA"]
        ADM: ["ADM0", "ADM1"]
    steps:
    - name: Create Build Call
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: NightlyBuild
        repo: wmgeolab/gbRelease
        token: ${{ secrets.DRTOKEN }}
        inputs: '{ "bType": "gbOpen", "ISO": ${{matrix.ISO}}, "ADM":${{matrix.ADM}}}'
