on:
  workflow_dispatch
  
name: xxNIGHTLY_gB
jobs:
  gbBuild:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          ISO: ["AFG","AGO","ALB","AND","ARE","ARG","ARM","ATA","ATG","AUS","AUT","AZE"]
          ADM: ["ADM0", "ADM1", "ADM2", "ADM3", "ADM4", "ADM5"]
          TYPE: ["gbOpen", "gbAuthoritative", "gbHumanitarian"]
    steps:
    - name: Check if build needed
      id: buildCheck
      continue-on-error: true
      run: |
           git clone https://github.com/wmgeolab/geoBoundaryBot
           python geoBoundaryBot/gbBuildCheck.py ${{secrets.DRTOKEN}} ${{matrix.ISO}} ${{matrix.ADM}} ${{matrix.TYPE}}
    
    - name: Create Build Call
      if: steps.buildCheck.outcome == 'success'
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: yDISPATCH_gBLayer
        repo: wmgeolab/geoBoundaries
        token: ${{ secrets.DRTOKEN }}
        inputs: '{ "bType": "${{matrix.TYPE}}", "ISO": "${{matrix.ISO}}", "ADM":"${{matrix.ADM}}"}'
    
    
    #["BDI", "BEL", "BEN", "BFA", "BGD", "BGR", "BHR", "BHS", "BIH", "BLR", "BLZ", "BOL"]

    
        
