on:
    workflow_dispatch

name: Nightly Run - A,B
jobs:
  gbBuild:
    runs-on: ubuntu-latest
    container: osgeo/gdal:ubuntu-small-latest
    steps:
    - name: Initialize Linux Environment
      run: |
           apt-get update
           apt-get install -y software-properties-common
           add-apt-repository ppa:git-core/ppa
           apt-get update
           apt-get install -y git
           curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
           apt-get install git-lfs
           apt-get install -y python3-pip
           apt-get install -y npm
           npm install -g mapshaper
           pip3 install geopandas
           pip3 install matplotlib
           pip3 install PyGithub
    
    - name: Download Repository Code
      uses: actions/checkout@v2.3.2
      with:
        lfs: true
        persist-credentials: false
        
    - name: Post-Download Initialization Steps
      run: |
           git fetch
           git clone https://github.com/wmgeolab/geoBoundaryBot
           
    - name: Checking Files
      id: checks
      run: |
           echo "==============================================="
           mkdir ~/tmp 
           mkdir ~/artifacts
           python geoBoundaryBot/gbBuild.py gbAuthoritative nightly A,B
           python geoBoundaryBot/gbBuild.py gbOpen nightly A,B
           python geoBoundaryBot/gbBuild.py gbHumanitarian nightly A,B
      env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    - name: Commit Files
      env:
            DRTOKEN: ${{secrets.DRTOKEN}}
            REP: ${{env.GITHUB_REPOSITORY}}
      run: |
           git config --local user.email "danr@wm.edu"
           git config --local user.name "DanRunfola"
           rm RESULT.txt
           git add -A .
           git diff-index --quiet HEAD || git commit -m "geoBoundary Status and Build Script"
           git status
           git remote set-url origin https://x-access-token:${{ secrets.DRTOKEN }}@github.com/$GITHUB_REPOSITORY
           git push origin master

       
        
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: ~/artifacts/
        

  
