on:
  workflow_dispatch
  
name: Nightly Spinups
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ISO: ["AFG"]#["AFG","AGO","ALB","AND","ARE","ARG","ARM","ATA","ATG","AUS","AUT","AZE"]
        ADM: ["ADM0"]#["ADM0", "ADM1", "ADM2", "ADM3", "ADM4", "ADM5"]
        TYPE: ["gbOpen", "gbAuthoritative", "gbHumanitarian"]
    steps:
    - name: Create nightly builds
      uses: wmgeolab/geoBoundariesBuildAction@main
      with:
       token: ${{secrets.DRTOKEN}}
       inputs: '{ "bType": "${{matrix.TYPE}}", "ISO": "${{matrix.ISO}}", "ADM":"${{matrix.ADM}}"}'
    #- name: Create Build Call
    #  uses: benc-uk/workflow-dispatch@v1
    #  with:
    #    workflow: NightlyBuild
    #    repo: wmgeolab/geoBoundaries
    #    token: ${{ secrets.DRTOKEN }}
    #    inputs: '{ "bType": "${{matrix.TYPE}}", "ISO": "${{matrix.ISO}}", "ADM":"${{matrix.ADM}}"}'
