on:
    workflow_dispatch:
        inputs:
            bType:
                description: Boundary Type (Required)
                required: true
            ISO:
                description: Boundary ISO (Required)
                required: true
            ADM:
                description: Boundary ADM Level
                required: true
                
name: yDISPATCH_gBLayer
jobs:
  gbBuild:
    runs-on: ubuntu-latest
    container: docker://geogdan/geoboundaries:A
    steps:
    - name: Git Clone
      run: |
           echo $GITHUB_WORKSPACE
           cd $GITHUB_WORKSPACE
           cd ..
           rm -r geoBoundaries
           GIT_LFS_SKIP_SMUDGE=1 git clone --depth 1 --branch main https://github.com/wmgeolab/geoBoundaries
           cd geoBoundaries
           git lfs pull --include "sourceData/${{github.event.inputs.bType}}/${{github.event.inputs.ISO}}_${{github.event.inputs.ADM}}.zip"
           git clone https://github.com/wmgeolab/geoBoundaryBot
           ls -l
    - name: Checking Files
      id: checks
      run: |
           echo "==============================================="
           mkdir ~/tmp 
           mkdir ~/artifacts
           python $GITHUB_WORKSPACE/geoBoundaryBot/gbBuild.py ${{github.event.inputs.bType}} nightly ${{github.event.inputs.ISO}} ${{github.event.inputs.ADM}} ${{secrets.DRTOKEN}}
      env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
    - name: Commit Files
      env:
            DRTOKEN: ${{secrets.DRTOKEN}}
            REP: ${{env.GITHUB_REPOSITORY}}
      run: |
           git config --local user.email "danr@wm.edu"
           git config --local user.name "DanRunfola"
           git config --global http.postBuffer 500M
           git config --global http.maxRequestBuffer 100M
           git config --global core.compression 0
           rm RESULT.txt
           git status
           git checkout .gitattributes
           git status
           find * -type f -size +99M -exec git lfs track --filename '{}' +
           git status
           git add -A .
           git status
           git commit -m "gB Nightly `date`"
           git status
           git pull
           git status
           git remote set-url origin https://x-access-token:${{ secrets.DRTOKEN }}@github.com/$GITHUB_REPOSITORY
           git push origin main
        
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: ~/artifacts/
